# usimg an existing docke image as a base
FROM alpine

# download an d install the dependency
RUN apk add --update redis
RUN apk add --update gcc

# Tell the image what to do when it start 
# as a container
CMD ["redis-server"]
